on:
  push:

jobs:
  install:
    runs-on: ubuntu-latest
    
    defaults:
      working-directory: node-app

    steps:
      - run: npm install --production
    
  tests:
    runs-on: ubuntu-latest
    
    defaults:
      working-directory: node-app

    steps:
      - run: npm run test
