on:
  push:

jobs:
  install:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: node-app

    steps:
      - uses: actions/checkout@v3
      - run: npm install
    
  tests:
    runs-on: ubuntu-latest
    
    needs: install

    defaults:
      run:
        working-directory: node-app

    steps:
      - uses: actions/checkout@v3
      - run: npm run test
