on:
  push:

jobs:
  install:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [12,14,16]
        os: [ubuntu-latest, windows]

    defaults:
      run:
        working-directory: node-app

    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run test
    
